version: '3.8'

services:
  api:
    image: hommel5957/hrmatrix:latest_dev
    container_name: hrmatrix_app
    ports:
      - "5000:8080"
    depends_on:
      - db
    volumes:
      - /var/www/uploads:/app/uploads
    networks:
      - hrmatrix-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  # Добавлена метка для Watchtower

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    restart: unless-stopped 
    environment:
      SA_PASSWORD: "QWEasdXZC756"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - hrmatrix-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --stop-timeout 300s
    networks:
      - hrmatrix-network

networks:
  hrmatrix-network:
    driver: bridge

volumes:
  dbdata:
